version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: productsdb
    ports:
      - "27017:27017"
  
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  app:
    build:
      context: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/productsdb?authSource=admin
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

